services:
  payload:
    image: renolation/wallie:latest
    ports:
      - '4567:3000'
    environment:
      - DATABASE_URI=postgresql://user:password@host:5432/wallie
      - PAYLOAD_SECRET=your-secret-key
      - PORT=3000
    restart: unless-stopped
